### ISSUE TITLE
zfs bad performance

### ISSUE THREAD

**Issue by hasufell** [ryao/zfs-overlay#9]
It lags and causes desktop freeze for a few seconds sometimes. ROOT is on SSD, no compression there (except the games subfolder).

Never experienced that with ext3/ext4. It may slow down the system a bit, but no lagging behavior.

**Comment by taozhijiang** [comment]
What's your system available RAM?

**Comment by hasufell** [comment]
at the time of writing it was something like 8gb I think

**Comment by kernelOfTruth** [comment]
@hasufell has the situation improved meanwhile ?

there were several changes that should indirectly or directly address these kind of "shortcomings" for desktop usage,

with the outstanding ABD2 merge (scatter gather) latency should be even lower and performance much better

**Comment by hasufell** [comment]
I don't use zfs anymore, so I cannot say.

**Comment by kernelOfTruth** [comment]
@hasufell that's a pity :(

if you still remember, could please post some more info on the issue so this could be tracked (perhaps specifically related to desktop usage) ?

e.g. you where just browsing the web and during scrolling the site and moving the mouse the screen content froze for a few seconds (?)

Thanks !
